# Generated by Django 5.2.7 on 2025-11-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_clientes', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('preferencias', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
